### GET ALL SUBJECTS OR FILTER BY 'subjectId' || 'authorId' || 'subject title'
### GET ALL SUBJECTS
GET http://localhost:3000/v1/subject
Content-Type: application/json

### GET FILTERED SUBJECTS
GET http://localhost:3000/v1/subject
Content-Type: application/json

{
    "author" : "authorId",
    "_id" : "subjectId",
    "title" : "subject title"
}


### ADD SUBJECT
## All these fields must be provided
POST http://localhost:3000/v1/subject
Content-Type: application/json

{
    "author" : "authorId",
    "title" : "exemple",
    "description" : "exemple",
    "date" : "date format string or unix timestamp"
}

### ADD SUBJECT REFERENCE
## All these fields must be provided
PUT http://localhost:3000/v1/subject
Content-Type: application/json

{
    "_id" : "subjectId",
    "reference" : "an url",
    "description" : "short description"
}



### UPDATE SUBJECT
### Subject id must be provided
### Updatable fields are : "title" "description"
PATCH http://localhost:3000/v1/user
Content-Type: application/json

{
    "_id" : "subject_id",
    "title" : "new title",
    "description" : "new description", 
}


### DELETE SUBJECT
DELETE http://localhost:3000/v1/user
Content-Type: application/json

{
    "_id" : "subject_id"
}