
### UPDATE USER
### User id must be provided
### Updatable fields are : "pseudo" "lastname" "firstname" "email"
PATCH http://localhost:3000/v1/user
Content-Type: application/json

{
    "_id" : "user_id",
    "pseudo" : "new pseudo",
    "lastname" : "new lastname", 
    "firstname" : "new firstname",
    "email" : "new email"
}


### DELETE USER
DELETE http://localhost:3000/v1/user
Content-Type: application/json

{
    "_id" : "user_id"
}